source "https://rubygems.org"

gem 'rails'

# Server
gem 'thin'

# View
gem 'haml'
gem 'jquery-rails'

# Assets
group :assets do
  gem 'sass-rails'
  gem 'bootstrap-sass'
  gem 'coffee-rails'
  gem 'uglifier'
end

group :production do
  gem 'pg'
end

group :development, :test do
  gem 'sqlite3'
end

group :test do
  gem 'foreman'
  gem 'rspec-rails'
  gem 'capybara'
  gem 'factory_girl_rails'
  gem 'simplecov', require: false
end
