source :rubygems

gem 'rails', '3.1.2'

# Server
gem 'thin'

# View
gem 'haml'
gem 'jquery-rails'

# Assets
group :assets do
  gem 'sass-rails'
  gem 'coffee-rails'
  gem 'uglifier'
end

group :production do
  gem 'pg'
end

group :development, :test do
  gem 'foreman'
  gem 'sqlite3'
  gem 'rspec-rails'
  gem 'guard'
  gem 'jasminerice'
end

group :test do
  gem 'spork', '>= 0.9.0.rc9
  gem 'guard-rspec'
  gem 'guard-spork'
  gem 'guard-jasmine'
  gem 'factory_girl_rails'
  gem 'capybara'
  gem 'simplecov', require: false
  gem 'rb-fsevent'
  gem 'ruby_gntp'
end
